# Generated by Django 6.1 on 2026-09-03 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_plan_usagemetric_planlimit_usagerecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='services.service'),
        ),
        migrations.AlterField(
            model_name='usagemetric',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='services.service'),
        ),
        migrations.AlterField(
            model_name='usagemetric',
            name='unit',
            field=models.CharField(help_text='Examples: emails, requests, GB, credits', max_length=50),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='services.usagemetric'),
        ),
    ]
